"""PostgreSQL storage, with isolated SQLite storage for local tests."""

import json
import os
import sqlite3
from collections.abc import Mapping
from contextlib import contextmanager
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env", override=False)


class FlexibleRow(Mapping):
    """Support both row['name'] and row[0] used by the existing API."""

    def __init__(self, names, values):
        self.names = names
        self.values = values
        self.data = dict(zip(names, values))

    def __getitem__(self, key):
        return self.values[key] if isinstance(key, int) else self.data[key]

    def __iter__(self):
        return iter(self.names)

    def __len__(self):
        return len(self.names)


def flex_row(cursor):
    if cursor.description is None:
        return lambda values: values
    names = [column.name for column in cursor.description]
    return lambda values: FlexibleRow(names, values)


class PostgresConnection:
    def __init__(self, raw):
        self.raw = raw

    def execute(self, query, params=()):
        sql = query.strip()
        if sql.upper() == "BEGIN IMMEDIATE":
            return None  # Psycopg starts a transaction with the first statement.
        if sql.upper().startswith("INSERT OR IGNORE INTO "):
            sql = "INSERT INTO " + sql[len("INSERT OR IGNORE INTO "):] + " ON CONFLICT DO NOTHING"
        return self.raw.execute(sql.replace("?", "%s"), params)


@contextmanager
def connection(root: Path, database_url: str | None = None):
    root.mkdir(parents=True, exist_ok=True)
    url = os.environ.get("DATABASE_URL", "") if database_url is None else database_url
    if url:
        import psycopg

        with psycopg.connect(url, row_factory=flex_row, connect_timeout=10) as raw:
            yield PostgresConnection(raw)
    else:
        db = sqlite3.connect(root / "ibc.sqlite3", timeout=20)
        db.row_factory = sqlite3.Row
        db.execute("PRAGMA foreign_keys=ON")
        try:
            yield db
            db.commit()
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()


SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS cases (
    id TEXT PRIMARY KEY, record TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1,
    review_status TEXT NOT NULL DEFAULT 'draft', created_at TEXT NOT NULL,
    reviewed_by TEXT, reviewed_at TEXT
);
CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id),
    filename TEXT NOT NULL, sha256 TEXT NOT NULL UNIQUE, source_url TEXT,
    extraction TEXT NOT NULL, created_at TEXT NOT NULL, content BLOB
);
CREATE TABLE IF NOT EXISTS audit (
    id INTEGER PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id),
    action TEXT NOT NULL, snapshot TEXT NOT NULL, actor TEXT, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS source_orders (
    id TEXT PRIMARY KEY, pdf_url TEXT NOT NULL UNIQUE,
    order_date TEXT, subject TEXT NOT NULL, remarks TEXT NOT NULL,
    bench_id TEXT, bench_name TEXT, first_seen_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL, pdf_status TEXT NOT NULL DEFAULT 'pending',
    pdf_error TEXT, pdf_sha256 TEXT, pdf_bytes INTEGER,
    pdf_prefix_bytes INTEGER, pdf_fetched_at TEXT,
    case_id TEXT REFERENCES cases(id)
);
CREATE INDEX IF NOT EXISTS source_orders_date_idx ON source_orders(order_date DESC);
CREATE INDEX IF NOT EXISTS source_orders_status_idx ON source_orders(pdf_status);
CREATE TABLE IF NOT EXISTS source_pages (
    filter_key TEXT NOT NULL, page_number INTEGER NOT NULL,
    fetched_at TEXT NOT NULL, row_count INTEGER NOT NULL,
    last_page INTEGER NOT NULL, PRIMARY KEY(filter_key, page_number)
);
CREATE TABLE IF NOT EXISTS source_page_failures (
    filter_key TEXT NOT NULL, page_number INTEGER NOT NULL,
    last_error TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 1,
    last_attempt_at TEXT NOT NULL, PRIMARY KEY(filter_key,page_number)
);
CREATE TABLE IF NOT EXISTS source_filters (
    key TEXT PRIMARY KEY, label TEXT NOT NULL, first_seen_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS source_order_filters (
    order_id TEXT NOT NULL REFERENCES source_orders(id), filter_key TEXT NOT NULL,
    PRIMARY KEY(order_id,filter_key)
);
"""

POSTGRES_SCHEMA = SQLITE_SCHEMA.replace("content BLOB", "content BYTEA").replace(
    "id INTEGER PRIMARY KEY, case_id", "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, case_id"
)


def initialize(root: Path, database_url: str | None = None):
    (root / "documents").mkdir(parents=True, exist_ok=True)
    url = os.environ.get("DATABASE_URL", "") if database_url is None else database_url
    if url:
        with connection(root, database_url=url) as db:
            for statement in POSTGRES_SCHEMA.split(";"):
                if statement.strip():
                    db.execute(statement)
            db.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS content BYTEA")
            db.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS subject TEXT")
            db.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS order_kind TEXT DEFAULT 'unknown'")
            db.execute("ALTER TABLE source_orders ADD COLUMN IF NOT EXISTS document_id TEXT REFERENCES documents(id)")
    else:
        with connection(root, database_url="") as db:
            db.executescript(SQLITE_SCHEMA)
            fields = {row["name"] for row in db.execute("PRAGMA table_info(documents)")}
            if "content" not in fields:
                db.execute("ALTER TABLE documents ADD COLUMN content BLOB")
            if "subject" not in fields:
                db.execute("ALTER TABLE documents ADD COLUMN subject TEXT")
            if "order_kind" not in fields:
                db.execute("ALTER TABLE documents ADD COLUMN order_kind TEXT DEFAULT 'unknown'")
            order_fields = {row['name'] for row in db.execute('PRAGMA table_info(source_orders)')}
            if 'document_id' not in order_fields:
                db.execute('ALTER TABLE source_orders ADD COLUMN document_id TEXT REFERENCES documents(id)')
    from .structured import initialize_structured
    with connection(root, database_url=url) as db:
        from .extraction import pdf_subject
        for row in db.execute("SELECT id,extraction FROM documents WHERE subject IS NULL").fetchall():
            extraction = json.loads(row["extraction"])
            if "subject" not in extraction:
                extraction["subject"], extraction["subject_source"] = pdf_subject(extraction["pages"])
            db.execute("UPDATE documents SET subject=?,extraction=? WHERE id=?",
                       (extraction.get("subject"), json.dumps(extraction), row["id"]))
        initialize_structured(db)
        # Backfill only unambiguous URL links; never infer a PDF from its case.
        for order in db.execute('SELECT id,pdf_url FROM source_orders WHERE document_id IS NULL').fetchall():
            matches = db.execute('SELECT id FROM documents WHERE source_url=? UNION SELECT document_id FROM import_files WHERE source_url=?',
                                 (order['pdf_url'], order['pdf_url'])).fetchall()
            if len(matches) == 1:
                db.execute('UPDATE source_orders SET document_id=? WHERE id=?', (matches[0][0], order['id']))
        from .automatic_orders import initialize_automatic
        from .document_matching import initialize_matching
        initialize_automatic(db)
        initialize_matching(db)
        # A single queryable catalogue combines listing metadata and stored files
        # without copying PDF bytes or creating a second source of truth.
        from .catalogue import ENTRIES
        if url:
            db.execute('CREATE OR REPLACE VIEW ibbi_order_catalogue AS ' + ENTRIES)
        else:
            db.execute('CREATE VIEW IF NOT EXISTS ibbi_order_catalogue AS ' + ENTRIES)


def decode(row):
    result = dict(row)
    result.pop("content", None)  # PDF bytes are served by the dedicated endpoint.
    for key in ("record", "extraction", "snapshot"):
        if key in result and isinstance(result[key], str):
            result[key] = json.loads(result[key])
    return result
